name: quick_memo_list
description: quickmemoandlist

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  firebase_auth: ^3.3.4
  provider: ^6.0.2
  firebase_core: ^1.10.6
  awesome_dialog: ^2.1.2
  cool_alert: ^1.1.0
  intl: ^0.17.0
  flutter_slidable: ^1.2.0
  flutter_feather_icons: ^2.0.0+1
  flutter_local_notifications: ^9.3.1
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
